import { useState } from "react";
import Link from "next/link";
import { ChapterAccess, Solution } from "./components/ProtectedContent";

const firstJava = `public class MeinStart
{
    public void begruessen()
    {
        System.out.println("Hallo, Informatik!");
    }

    public int verdoppeln(int zahl)
    {
        return zahl * 2;
    }
}`;
const firstJavaScript = `let anzahl = 3;
let preis = 2;
let gesamt = anzahl * preis;
console.log(gesamt);`;

function CopyCode({ children, label }: { children: string; label: string }) {
  const [message, setMessage] = useState("");
  async function copy() {
    try { await navigator.clipboard.writeText(children); setMessage("Kopiert. Du kannst den Text jetzt einfügen."); }
    catch { setMessage("Bitte markiere den Code und kopiere ihn über das Menü deines Geräts."); }
  }
  return <div className="starterCode"><div><strong>{label}</strong><button onClick={copy}>Code kopieren</button></div><pre><code>{children}</code></pre><span role="status">{message}</span></div>;
}

export default function ToolsPage() {
  const [amount, setAmount] = useState(3);
  const [price, setPrice] = useState(2);
  return <main>
    <nav className="nav shell"><Link className="brand" href="/"><span className="brandMark">&lt;/&gt;</span><span>Informatik-Lernlabor</span></Link><Link href="/#themen">← Zu den Kapiteln</Link></nav>
    <header className="subpageHero shell"><span className="eyebrow">WERKZEUGE KENNENLERNEN · DEIN ERSTES PROGRAMM</span><h1>Du musst noch<br /><em>nichts können.</em></h1><p>Was ist eine Entwicklungsumgebung? Wo tippe ich etwas ein? Was muss ich anklicken? Diese Einführung begleitet dich vom ersten Fenster bis zum ersten selbst getesteten Programm.</p><div className="heroActions"><a href="#bluej" className="primaryButton">Mit BlueJ starten ↓</a><a href="#javascript" className="textButton">JavaScript im Browser ↓</a><a href="#scratch" className="textButton">Scratch kennenlernen ↓</a></div></header>
    <div className="toolsContent shell">
      <section className="lessonSection"><h2>Programm und Sprache sind zwei verschiedene Dinge</h2><p>Ein Programm ist eine Folge genauer Anweisungen. Damit der Computer sie ausführen kann, schreiben wir sie in einer Programmiersprache. Eine Entwicklungsumgebung hilft beim Schreiben und Ausprobieren – wie ein gut ausgestatteter Arbeitsplatz.</p><div className="lessonTableWrap" role="region" aria-label="Übersichtstabelle" tabIndex={0}><table className="lessonTable"><thead><tr><th>Begriff</th><th>Was ist das?</th><th>Wo arbeiten wir?</th></tr></thead><tbody><tr><td>Java</td><td>Eine Programmiersprache mit Klassen und Objekten.</td><td>Wir schreiben Java in BlueJ.</td></tr><tr><td>BlueJ</td><td>Ein Programm zum Schreiben, Übersetzen und Testen von Java.</td><td>Im BlueJ-Fenster auf dem Schulcomputer.</td></tr><tr><td>JavaScript</td><td>Eine andere Programmiersprache, die unter anderem in Webbrowsern läuft.</td><td>Für den Einstieg in der Browser-Konsole.</td></tr><tr><td>Scratch</td><td>Eine blockbasierte Programmierumgebung.</td><td>Blöcke werden mit der Maus zu Programmen verbunden.</td></tr><tr><td>SQL</td><td>Eine Sprache zum Arbeiten mit Datenbanken.</td><td>In einer Datenbankumgebung; SQL ist weder Java noch JavaScript.</td></tr></tbody></table></div><aside className="rememberBox"><span>MERKSATZ</span><p>Java und JavaScript sind unterschiedliche Sprachen. BlueJ ist unser Werkzeug für Java. Wähle die Sprache, die im Arbeitsauftrag steht.</p></aside><p>Für Zahlensysteme, Tabellenmodelle und die ersten SQL-Aufgaben genügen Papier und Stift. Du musst diese Werkzeuge also nicht alle vor dem ersten Kapitel beherrschen.</p></section>

      <section className="lessonSection" id="bluej"><span className="eyebrow">WEG 1 · JAVA MIT BLUEJ</span><h2>BlueJ: So findest du dich zurecht</h2><p>Öffne BlueJ auf dem Schulcomputer. Falls es dort noch nicht eingerichtet ist, lasse dir das von deiner Lehrkraft zeigen. Je nach Spracheinstellung stehen auf den Knöpfen deutsche oder englische Wörter. Form und Farbe können von der Skizze abweichen; die Aufgaben der Bereiche bleiben gleich.</p>
        <figure className="interfaceFigure"><div className="bluejMock"><div className="mockToolbar">Projekt / Project · Bearbeiten / Edit · Werkzeuge / Tools · Ansicht / View</div><div className="mockWorkspace"><aside><b>①</b><span>Neue Klasse</span><span>Übersetzen</span></aside><div><b>② Klassenübersicht</b><div className="mockClass">MeinStart</div><p>Ein Kasten ist ein Bauplan für Objekte.</p></div></div><div className="mockBench"><b>③ Objektbank</b><span>meinStart1 : MeinStart</span></div></div><figcaption>Schematische BlueJ-Oberfläche, kein Bildschirmfoto. ① Werkzeuge · ② Klassen · ③ erzeugte Objekte.</figcaption></figure>
        <ol className="explainList"><li><strong>Projektfenster:</strong> Hier siehst du, welche Klassen zu deinem Programm gehören. Ein Projekt ist ein Ordner mit zusammengehörigen Dateien.</li><li><strong>Editor:</strong> Ein Doppelklick auf einen Klassenkasten öffnet den Text mit den Anweisungen. Diesen Text nennt man Quellcode.</li><li><strong>Objektbank:</strong> Unten liegen konkrete Objekte, die du aus einer Klasse erzeugst. Der Kasten oben ist der Bauplan; ein Objekt unten ist ein daraus erstelltes Exemplar.</li><li><strong>Terminal:</strong> Ein zusätzliches Fenster zeigt Textausgaben. Es erscheint, wenn dein Programm etwas ausgibt. Es ist kein Fehlerfenster.</li></ol>
        <h3>Schritt 1: Ein Projekt und eine Klasse anlegen</h3><ol className="explainList"><li>Wähle <strong>Projekt → Neues Projekt</strong> beziehungsweise <strong>Project → New Project</strong>.</li><li>Wähle einen wiederauffindbaren Ordner und nenne das Projekt <code>MeinErstesProgramm</code>.</li><li>Klicke auf <strong>Neue Klasse / New Class</strong>. Schreibe als Namen genau <code>MeinStart</code>. Wähle eine normale Java-Klasse, falls mehrere Vorlagen angezeigt werden.</li><li>Öffne den Kasten <code>MeinStart</code> mit einem Doppelklick. Jetzt siehst du den Editor.</li><li>Markiere den gesamten vorgegebenen Beispieltext und ersetze ihn durch das folgende Programm. Übernimm auch die geschweiften Klammern.</li></ol>
        <CopyCode label="Java · vollständiger Inhalt der Klasse MeinStart" >{firstJava}</CopyCode>
        <h3>Schritt 2: Den Code lesen</h3><p><code>public class MeinStart</code> gibt dem Bauplan seinen Namen. Groß- und Kleinschreibung zählen. Die äußeren Klammern umfassen die ganze Klasse. Darin stehen zwei Methoden: <code>begruessen</code> und <code>verdoppeln</code>. Eine Methode ist eine benannte Tätigkeit, die du gezielt starten kannst.</p><p><code>public void begruessen()</code> bedeutet hier: Die Methode ist von außen aufrufbar, bekommt keine Eingabe zwischen den runden Klammern und liefert keinen Rückgabewert. <code>System.out.println(...)</code> schreibt stattdessen Text ins Terminal. Der Text steht in geraden doppelten Anführungszeichen. Das Semikolon schließt diese Anweisung ab.</p><p><code>public int verdoppeln(int zahl)</code> bekommt eine ganze Zahl als Eingabe. <code>int</code> steht für ganze Zahlen. <code>return zahl * 2;</code> liefert das Doppelte zurück. Ein Rückgabewert wird beim Methodenaufruf in BlueJ angezeigt; er ist etwas anderes als eine Textausgabe im Terminal. Du musst die Fachwörter noch nicht auswendig können – beobachte zuerst den Unterschied.</p>
        <h3>Schritt 3: Übersetzen, Objekt erzeugen, Methode starten</h3><ol className="lessonFlow"><li><span>1</span><p>Klicke im Editor auf <strong>Übersetzen / Compile</strong>. BlueJ prüft den Java-Text und übersetzt ihn. Eine erfolgreiche Übersetzung führt das Programm noch nicht aus.</p></li><li><span>2</span><p>Gehe zum Projektfenster zurück. Öffne mit der rechten Maustaste das Menü des Kastens <strong>MeinStart</strong>. Wähle <code>new MeinStart()</code>. Damit entsteht ein Objekt. Den vorgeschlagenen Objektnamen kannst du bestätigen.</p></li><li><span>3</span><p>Unten erscheint das Objekt auf der Objektbank. Öffne dessen Menü mit der rechten Maustaste und wähle <code>void begruessen()</code>. Im Terminal steht nun <strong>Hallo, Informatik!</strong></p></li><li><span>4</span><p>Öffne noch einmal das Menü des Objekts und wähle <code>int verdoppeln(int zahl)</code>. Trage <strong>4</strong> ein und bestätige. BlueJ zeigt den Rückgabewert <strong>8</strong>.</p></li></ol><p>Auf einem Trackpad entspricht ein Klick mit zwei Fingern häufig dem Rechtsklick. Nutze bei Bedarf das Kontextmenü deiner Maus. Wenn du den Code änderst, übersetze ihn erneut. Erzeuge anschließend bei Bedarf ein neues Objekt, bevor du die Änderung ausprobierst.</p>
        <h3>Fehler gehören dazu: So findest du die Ursache</h3><div className="lessonTableWrap" role="region" aria-label="Übersichtstabelle" tabIndex={0}><table className="lessonTable"><thead><tr><th>Beobachtung</th><th>Das kannst du prüfen</th></tr></thead><tbody><tr><td>Die Klasse wird nicht übersetzt.</td><td>Ist der Name überall MeinStart? Sind Anführungszeichen, Klammern und Semikolons vollständig?</td></tr><tr><td>Übersetzen klappt, aber es erscheint kein Gruß.</td><td>Hast du ein Objekt erzeugt und seine Methode begruessen gestartet?</td></tr><tr><td>Das Menü zeigt keine Methode.</td><td>Klickst du auf das Objekt unten und wurde die Klasse nach der Änderung übersetzt?</td></tr><tr><td>Die Eingabe wird abgelehnt.</td><td>verdoppeln erwartet eine ganze Zahl wie 4. Schreibe hier weder vier noch "4".</td></tr><tr><td>Ich finde einen falschen Wert nicht.</td><td>Teste zuerst ein kleines Beispiel, dessen Ergebnis du im Kopf kennst.</td></tr></tbody></table></div>
        <p>Später lernst du den <strong>Objektinspektor</strong> kennen: Über „Inspect / Inspizieren“ im Menü eines Objekts kannst du seine gespeicherten Werte betrachten. Der <strong>Debugger</strong> hilft dir, ein Programm anzuhalten und Anweisungen einzeln zu verfolgen. Beides ist für deinen ersten Gruß noch nicht nötig.</p>
      </section>

      <section className="lessonSection" id="javascript"><span className="eyebrow">WEG 2 · JAVASCRIPT IM BROWSER</span><h2>Eine Konsole ist ein Platz zum Ausprobieren</h2><p>Für kleine JavaScript-Experimente benötigst du einen aktuellen Browser. Die Konsole ist ein Bereich seiner Entwicklerwerkzeuge: Du gibst einen Ausdruck oder eine Anweisung ein und siehst ein Ergebnis oder eine Fehlermeldung. Sie ist nicht die Adresszeile für Internetadressen.</p><ol className="explainList"><li>Öffne einen leeren neuen Browser-Tab. So arbeitest du auf einer eigenen Übungsseite.</li><li>In Chrome oder Edge: Öffne das Drei-Punkte-Menü, <strong>Weitere Tools → Entwicklertools</strong>, danach den Reiter <strong>Konsole / Console</strong>. In Firefox: <strong>Weitere Werkzeuge → Werkzeuge für Web-Entwickler</strong>, dann <strong>Konsole</strong>. Namen können je nach Version leicht variieren.</li><li>Klicke neben das Eingabezeichen <code>&gt;</code>. Tippe <code>2 + 3</code> und drücke Enter. Das Ergebnis ist <code>5</code>.</li><li>Tippe <code>console.log("Hallo, Informatik!");</code> und drücke Enter. Der Text wird ausgegeben. Eine zusätzliche Anzeige <code>undefined</code> ist hier normal: Die Ausgabe-Anweisung liefert keinen eigenen Rückgabewert.</li></ol>
        <figure className="interfaceFigure"><div className="consoleMock"><div className="mockToolbar">Elemente &nbsp; <strong>① Konsole</strong> &nbsp; Quellen &nbsp; Netzwerk</div><pre>{`② > 2 + 3
③   5
   > console.log("Hallo, Informatik!");
    Hallo, Informatik!
    undefined`}</pre></div><figcaption>Schematische Konsole: ① Reiter auswählen · ② eigene Eingabe · ③ Ausgabe darunter lesen.</figcaption></figure>
        <h3>Variablen: Werte unter einem Namen merken</h3><p>Stell dir drei Hefte zum Preis von jeweils zwei Euro vor. Wir merken uns die Anzahl und den Einzelpreis in Variablen. <code>let</code> legt eine Variable an. Das Gleichheitszeichen <code>=</code> weist ihr einen Wert zu. Es ist hier eine Speicheranweisung, keine Frage, ob zwei Seiten gleich sind.</p><CopyCode label="JavaScript · jede Zeile einzeln eingeben">{firstJavaScript}</CopyCode><p>Nach den ersten drei Zeilen darf die Konsole jeweils <code>undefined</code> anzeigen. Erst die vierte Zeile gibt das Ergebnis <code>6</code> aus. Das Sternchen <code>*</code> steht für Multiplikation. Rechne zuerst selbst, was bei fünf Heften herauskommen müsste.</p><p>Ändere eine vorhandene Variable mit <code>anzahl = 5;</code>. Schreibe dabei kein neues <code>let</code>. Berechne danach <code>gesamt = anzahl * preis;</code> erneut und gib <code>console.log(gesamt);</code> ein. Eine Variable speichert einen Wert; sie wird nicht automatisch wie eine Tabellenkalkulationsformel neu berechnet.</p>
        <div className="calculationModel"><h3>Rechenmodell zum Beobachten</h3><p>Diese Regler zeigen die Rechnung aus dem Beispiel. Den JavaScript-Code führst du in deiner Browser-Konsole aus.</p><label>Anzahl der Hefte <input type="number" min="0" max="20" value={amount} onChange={(event) => setAmount(Math.max(0, Math.min(20, Number(event.target.value))))} /></label><label>Preis pro Heft in Euro <input type="number" min="0" max="20" value={price} onChange={(event) => setPrice(Math.max(0, Math.min(20, Number(event.target.value))))} /></label><output aria-live="polite">{amount} × {price} = {(amount * price).toLocaleString("de-DE")} €</output></div>
        <h3>Drei typische Stolperstellen</h3><ul className="explainList"><li><strong>Zahl oder Text:</strong> <code>2 + 3</code> ergibt <code>5</code>. <code>"2" + "3"</code> verbindet zwei Texte zu <code>"23"</code>. Anführungszeichen ändern die Bedeutung.</li><li><strong>Name schon vergeben:</strong> Falls „Identifier has already been declared“ erscheint, wurde derselbe Name mit <code>let</code> noch einmal angelegt. Weise der vorhandenen Variable einen Wert ohne <code>let</code> zu oder lade den leeren Übungstab neu und beginne wieder oben.</li><li><strong>Schreibweise:</strong> <code>console.log</code> muss genau so geschrieben werden. <code>Console.Log</code> ist ein anderer Name. Nutze Dezimalpunkte im Code, zum Beispiel <code>2.5</code>.</li></ul><p>Manche Browser blockieren das Einfügen von Code zunächst. Tippe die kurzen Übungen dann selbst. Führe in der Konsole nur Anweisungen aus, die du verstehen und erklären kannst.</p>
      </section>
      <section className="lessonSection" id="scratch"><span className="eyebrow">WEG 3 · MIT BLÖCKEN BEGINNEN</span><h2>Scratch: Ziehen, verbinden, starten</h2><p>Öffne <a href="https://scratch.mit.edu/projects/editor/" target="_blank" rel="noreferrer">den Scratch-Editor</a>. Links findest du farbige Blockgruppen, in der Mitte setzt du das Programm zusammen. Rechts siehst du die Bühne mit einer Figur. Unter der Bühne wählst du die Figur aus, deren Programm du bearbeitest.</p><ol className="explainList"><li>Ziehe aus <strong>Ereignisse</strong> den Block „Wenn grüne Flagge angeklickt wird“ in den mittleren Bereich.</li><li>Hänge aus <strong>Aussehen</strong> einen „sage … für 2 Sekunden“-Block darunter. Trage „Hallo, Informatik!“ ein.</li><li>Klicke oberhalb der Bühne auf die grüne Flagge. Die Figur zeigt den Text.</li><li>Lege unter <strong>Variablen</strong> eine Variable <code>anzahl</code> an. Mit „setze anzahl auf 3“ weist du ihr einen Wert zu. Im Zahlenfeld kannst du auch einen grünen Rechenblock verwenden.</li><li>Speichere dein Projekt über <strong>Datei → Auf deinem Computer speichern</strong> als .sb3-Datei und öffne es später über „Von deinem Computer hochladen“.</li></ol><p>In den späteren Arbeitsaufträgen beschreiben die Blocklisten den Ablauf. Suche den passenden Block in seiner Kategorie und passe Namen und Werte an. Listenplätze beginnen in Scratch bei 1; Java-Arrays beginnen bei 0. Diese beiden Zählweisen wirst du im Sortierkapitel vergleichen.</p></section>
      <ChapterAccess scope="werkzeuge" />
      <section className="guidedTasks"><h2>Vier kleine erste Aufgaben</h2>{[
        {id:"start-1",title:"BlueJ: Begrüßung verändern",text:"Ändere den Gruß in der Klasse MeinStart. Übersetze erneut, erzeuge ein Objekt und rufe die Methode auf. Notiere die drei notwendigen Aktionen und die tatsächliche Ausgabe.",hint:"Übersetzen und Ausführen sind zwei getrennte Schritte."},
        {id:"start-2",title:"BlueJ: Aus doppelt wird dreifach",text:"Ergänze eine neue Methode verdreifachen(int zahl). Teste sie mit 0, 4 und −2. Notiere für jeden Test zuerst deine Erwartung.",hint:"Orientiere dich an verdoppeln. Ändere den Methodennamen und einen Faktor."},
        {id:"start-3",title:"JavaScript: Ein zweiter Einkauf",text:"Berechne in der Konsole den Preis von vier Stiften zu je 1.50 Euro. Erhöhe danach die Anzahl auf sechs und berechne den Gesamtpreis erneut. Erkläre jede Zeile.",hint:"Verwende einen Punkt in 1.50. Nach dem Ändern der Anzahl musst du auch den Gesamtwert neu berechnen."},
        {id:"start-4",title:"Scratch: Drei Grüße",text:"Lasse die Figur dreimal nacheinander einen selbst gewählten Gruß jeweils zwei Sekunden lang anzeigen. Beschreibe, welche Blöcke du benutzt hast.",hint:"Unter Steuerung findest du einen wiederhole-Block. Der sage-Block gehört in seinen Innenraum."}
      ].map((task) => <article className="guidedTask" key={task.id}><span className="taskId">{task.id}</span><h3>{task.title}</h3><p>{task.text}</p><details><summary>Hinweis</summary><p>{task.hint}</p></details><Solution scope="werkzeuge" id={task.id} /></article>)}</section>
      <p className="sourceNote">Anleitungen zum Nachschlagen: <a href="https://www.bluej.org/tutorial/tutorial.pdf" target="_blank" rel="noreferrer">offizielles BlueJ-Tutorial</a> · <a href="https://developer.mozilla.org/de/docs/Web/JavaScript/Guide/Introduction" target="_blank" rel="noreferrer">JavaScript-Einstieg bei MDN</a> · <a href="https://scratch.mit.edu/ideas" target="_blank" rel="noreferrer">Scratch-Ideen und Tutorials</a>. Die Skizzen dienen zur Orientierung; genaue Menünamen hängen von Version und Sprache ab.</p>
    </div><footer><div className="shell"><Link href="/#themen">Zu den Kapiteln →</Link><a href="#bluej">Zur BlueJ-Einführung ↑</a></div></footer>
  </main>;
}
