name: Website automatisch veröffentlichen

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Dateien laden
        uses: actions/checkout@v7

      - name: Node.js einrichten
        uses: actions/setup-node@v7
        with:
          node-version: 24
          package-manager-cache: false

      - name: Abhängigkeiten installieren
        run: npm install

      - name: Website erstellen
        run: npm run build

      - name: GitHub Pages vorbereiten
        uses: actions/configure-pages@v5

      - name: Website hochladen
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./docs

      - name: Website veröffentlichen
        id: deployment
        uses: actions/deploy-pages@v4
